### ISSUE TITLE
Question - HA multi-AZ VPN setup

### ISSUE THREAD

**Issue by gkze** [bobtfish/AWSnycast#18]
Is it possible to use this to set up 3 instances (1 in each AZ) such that I could connect to 1 IP and also have automatic failover in case any of the instances dies?

**Comment by bobtfish** [comment]
Yes :)

I'll need some more details about what you actually want to do to help in
more detail though.

On 2 Aug 2016 06:37, "George Kontridze" <notifications@github.com> wrote:

Is it possible to use this to set up 3 instances (1 in each AZ) such that I
could connect to 1 IP and also have automatic failover in case any of the
instances dies?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bobtfish/AWSnycast/issues/18>, or mute the thread

**Comment by gkze** [comment]
So I have a VPC with 6 subnets -- 3 private, 3 public (all under a 10/16 block). I want to be able to create an instance in each of the public subnets and install an IPSec VPN solution (thinking libreswan/xl2tpd) on each of them. I also want to have the 3 instances share 1 IP that I can use to distribute to users. If any of the instances fail, I still want to be able to connect to ones that didn't.

That's about as far as I've throught it through :)

**Comment by bobtfish** [comment]
Mm, to get a public IP, you'd need an ENI (and to fail that ENI over between instances). This is possible as AWSnycast has hooks to run on takeover, but it's a little out of it's area (as generally you take over an IP in the private space).

You may actually be better here with a more 'traditional' solution like keepalived (running in unicast mode).

**Comment by gkze** [comment]
Got it, thank you @bobtfish! Will look into keepalived instead.
